import type { Product, Vendor, Order, DeliveryTask, Category } from "./types";

export const CATEGORIES: Category[] = [
  { id: "all",                label: "All", active: true,  comingSoon: false },
  { id: "building-materials", label: "Building Materials", active: true,  comingSoon: false },
  { id: "modern-furniture",   label: "Modern Furniture", active: false, comingSoon: true  },
  { id: "fashion-lifestyle",  label: "Fashion & Lifestyle", active: false, comingSoon: true  },
  { id: "essential-products", label: "Essential Products", active: false, comingSoon: true  },
];

export const VENDORS: Vendor[] = [
  {
    id: "vendor-1",
    name: "Kilimanjaro Hardware",
    location: "Arusha CBD — Sokoine Rd",
    rating: 4.8,
    total_sales: 8450000,
    commission_rate: 0.08,
    wallet_balance: 7774000,
    products_count: 7,
    status: "active",
  },
  {
    id: "vendor-2",
    name: "Safari Building Supplies",
    location: "Kaloleni — Nairobi Rd",
    rating: 4.5,
    total_sales: 5200000,
    commission_rate: 0.08,
    wallet_balance: 4784000,
    products_count: 5,
    status: "active",
  },
  {
    id: "vendor-3",
    name: "Jua Kali Mabati Works",
    location: "Sakina — Moshi Rd",
    rating: 4.6,
    total_sales: 3900000,
    commission_rate: 0.08,
    wallet_balance: 3588000,
    products_count: 4,
    status: "active",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Dangote Cement 50kg",
    category: "building-materials",
    vendor_id: "vendor-1",
    price: 18500,
    unit: "bag",
    stock: 250,
    description: "High-strength Portland cement. Ideal for foundations, columns, and structural work. Grade 42.5N, consistent quality batch after batch.",
    specs: { "Weight": "50 kg", "Grade": "42.5N", "Setting Time": "30–45 min", "Origin": "Tanzania" },
    gradientFrom: "#3a2a1a",
    gradientTo: "#1a1208",
    in_stock: true,
    featured: true,
  },
  {
    id: "p2",
    name: "Simba Cement 50kg",
    category: "building-materials",
    vendor_id: "vendor-2",
    price: 17000,
    unit: "bag",
    stock: 180,
    description: "Locally produced Simba cement. Excellent for plastering, brickwork, and general construction. Grade 32.5R.",
    specs: { "Weight": "50 kg", "Grade": "32.5R", "Setting Time": "45–60 min", "Origin": "Tanzania" },
    gradientFrom: "#2a1a0a",
    gradientTo: "#150d05",
    in_stock: true,
    featured: false,
  },
  {
    id: "p3",
    name: "Reinforcement Steel Rod 12mm",
    category: "building-materials",
    vendor_id: "vendor-1",
    price: 45000,
    unit: "piece",
    stock: 500,
    description: "High-tensile deformed steel bar, 12mm diameter, 12m length. BS4449 standard. Perfect for slab and beam reinforcement.",
    specs: { "Diameter": "12 mm", "Length": "12 m", "Standard": "BS4449", "Weight": "~10.6 kg" },
    gradientFrom: "#1a2030",
    gradientTo: "#0d1018",
    in_stock: true,
    featured: true,
  },
  {
    id: "p4",
    name: "Reinforcement Steel Rod 16mm",
    category: "building-materials",
    vendor_id: "vendor-1",
    price: 65000,
    unit: "piece",
    stock: 320,
    description: "Heavy-duty 16mm deformed rebar, 12m length. Used in columns, large slabs, and retaining walls. High-tensile Grade 460.",
    specs: { "Diameter": "16 mm", "Length": "12 m", "Grade": "460", "Weight": "~18.9 kg" },
    gradientFrom: "#1a1820",
    gradientTo: "#0d0c10",
    in_stock: true,
    featured: false,
  },
  {
    id: "p5",
    name: "Mabati Iron Sheet 26G (8ft)",
    category: "building-materials",
    vendor_id: "vendor-3",
    price: 32000,
    unit: "sheet",
    stock: 400,
    description: "Corrugated galvanised iron roofing sheet, 26 gauge, 8 feet long. Pre-painted box profile. Rust-resistant treatment.",
    specs: { "Gauge": "26G", "Length": "8 ft (2.44m)", "Width": "0.9 m", "Profile": "Box Rib" },
    gradientFrom: "#102030",
    gradientTo: "#080f18",
    in_stock: true,
    featured: true,
  },
  {
    id: "p6",
    name: "Mabati Iron Sheet 28G (10ft)",
    category: "building-materials",
    vendor_id: "vendor-3",
    price: 38500,
    unit: "sheet",
    stock: 280,
    description: "Long-span 28 gauge roofing sheet, 10 feet. Ideal for larger roof spans. High-rib corrugated profile for added strength.",
    specs: { "Gauge": "28G", "Length": "10 ft (3.05m)", "Width": "0.9 m", "Profile": "Corrugated" },
    gradientFrom: "#0f1a20",
    gradientTo: "#070d10",
    in_stock: true,
    featured: false,
  },
  {
    id: "p7",
    name: "Clay Bricks (per 1,000)",
    category: "building-materials",
    vendor_id: "vendor-2",
    price: 185000,
    unit: "lot",
    stock: 50,
    description: "Kiln-fired clay bricks, standard size. Uniform shape and high compressive strength. Ideal for load-bearing and partition walls.",
    specs: { "Size": "230×110×76 mm", "Qty": "1,000 bricks", "Type": "Kiln-fired", "Compressive Strength": ">10 N/mm²" },
    gradientFrom: "#2a1510",
    gradientTo: "#150a08",
    in_stock: true,
    featured: true,
  },
  {
    id: "p8",
    name: "Washed River Sand (1 tonne)",
    category: "building-materials",
    vendor_id: "vendor-2",
    price: 65000,
    unit: "tonne",
    stock: 80,
    description: "Clean, washed river sand. Fine grade for plastering and concrete mixing. Delivered by tipper truck within Arusha.",
    specs: { "Grade": "Fine", "Delivery": "By tipper", "Min Order": "1 tonne", "Use": "Plaster & Concrete" },
    gradientFrom: "#201a10",
    gradientTo: "#100d08",
    in_stock: true,
    featured: false,
  },
  {
    id: "p9",
    name: "Crushed Ballast (1 tonne)",
    category: "building-materials",
    vendor_id: "vendor-2",
    price: 75000,
    unit: "tonne",
    stock: 60,
    description: "Crushed stone aggregate for concrete mixing. 20mm to 40mm size range. Clean, angular fragments for strong concrete mixes.",
    specs: { "Size": "20–40 mm", "Delivery": "By tipper", "Min Order": "1 tonne", "Use": "Concrete mix" },
    gradientFrom: "#181820",
    gradientTo: "#0c0c10",
    in_stock: true,
    featured: false,
  },
  {
    id: "p10",
    name: "Crown Paints Silk White 20L",
    category: "building-materials",
    vendor_id: "vendor-1",
    price: 95000,
    unit: "tin",
    stock: 45,
    description: "Premium silk emulsion wall paint. Low sheen, washable, and moisture-resistant. Coverage ~130 m² per 20L tin with two coats.",
    specs: { "Volume": "20 L", "Finish": "Silk / Low Sheen", "Coverage": "~130 m²", "Drying Time": "2 hrs recoat" },
    gradientFrom: "#1a1a2a",
    gradientTo: "#0d0d15",
    in_stock: true,
    featured: false,
  },
  {
    id: "p11",
    name: "PVC Water Pipe 4\" (6m)",
    category: "building-materials",
    vendor_id: "vendor-3",
    price: 28000,
    unit: "piece",
    stock: 120,
    description: "uPVC pressure pipe, Class C, 4-inch diameter, 6m length. For cold water supply, irrigation, and drainage systems.",
    specs: { "Diameter": "4\" (110mm)", "Length": "6 m", "Class": "C (6 bar)", "Standard": "KS 02-96" },
    gradientFrom: "#0a1820",
    gradientTo: "#050c10",
    in_stock: true,
    featured: false,
  },
  {
    id: "p12",
    name: "PVC Drainage Pipe 6\" (3m)",
    category: "building-materials",
    vendor_id: "vendor-3",
    price: 19500,
    unit: "piece",
    stock: 90,
    description: "Heavy-duty uPVC drainage pipe, 6-inch bore, 3m length. Smooth internal bore for fast flow. Includes push-fit rubber seal joint.",
    specs: { "Diameter": "6\" (160mm)", "Length": "3 m", "Type": "Drainage/Sewer", "Joint": "Push-fit rubber" },
    gradientFrom: "#101820",
    gradientTo: "#080c10",
    in_stock: true,
    featured: false,
  },
  {
    id: "p13",
    name: "Floor Tiles 60×60cm (per m²)",
    category: "building-materials",
    vendor_id: "vendor-1",
    price: 22000,
    unit: "m²",
    stock: 300,
    description: "Porcelain floor tiles, polished finish. Slip-resistant texture. Suitable for indoor floors, verandas, and light commercial areas.",
    specs: { "Size": "60×60 cm", "Finish": "Polished", "PEI Rating": "Class 4", "Thickness": "8 mm" },
    gradientFrom: "#1a1520",
    gradientTo: "#0d0a10",
    in_stock: true,
    featured: true,
  },
  {
    id: "p14",
    name: "Wall Tiles 30×60cm (per m²)",
    category: "building-materials",
    vendor_id: "vendor-1",
    price: 18000,
    unit: "m²",
    stock: 200,
    description: "Ceramic wall tiles with matte finish. Water-resistant and easy to clean. Ideal for bathrooms, kitchens, and feature walls.",
    specs: { "Size": "30×60 cm", "Finish": "Matte", "Water Absorption": "<3%", "Thickness": "6.5 mm" },
    gradientFrom: "#151820",
    gradientTo: "#0a0c10",
    in_stock: true,
    featured: false,
  },
  {
    id: "p15",
    name: "BRC Wire Mesh A142",
    category: "building-materials",
    vendor_id: "vendor-2",
    price: 55000,
    unit: "sheet",
    stock: 75,
    description: "Welded steel fabric reinforcement, A142 specification. 6m×2.4m sheet. Used in ground slabs, suspended slabs, and roads.",
    specs: { "Spec": "A142", "Size": "6×2.4 m", "Wire Size": "6 mm", "Mesh Size": "200×200 mm" },
    gradientFrom: "#181520",
    gradientTo: "#0c0a10",
    in_stock: true,
    featured: false,
  },
];

export const ORDERS: Order[] = [
  {
    id: "FS-1042",
    customer_name: "John Mollel",
    customer_phone: "0712 345 678",
    items: [
      { product_id: "p1", product_name: "Dangote Cement 50kg", qty: 20, unit_price: 18500, unit: "bag", subtotal: 370000, vendor_id: "vendor-1" },
      { product_id: "p3", product_name: "Steel Rod 12mm", qty: 10, unit_price: 45000, unit: "piece", subtotal: 450000, vendor_id: "vendor-1" },
    ],
    total: 820000,
    commission: 65600,
    vendor_payout: 754400,
    delivery_fee: 8000,
    status: "delivered",
    delivery_address: "Njiro, Arusha",
    created_at: "2026-03-25T09:30:00Z",
    notes: "Deliver by morning",
  },
  {
    id: "FS-1043",
    customer_name: "Amina Rashidi",
    customer_phone: "0754 987 321",
    items: [
      { product_id: "p5", product_name: "Mabati Iron Sheet 26G", qty: 30, unit_price: 32000, unit: "sheet", subtotal: 960000, vendor_id: "vendor-3" },
    ],
    total: 960000,
    commission: 76800,
    vendor_payout: 883200,
    delivery_fee: 10000,
    status: "dispatched",
    delivery_address: "Kijenge, Arusha",
    created_at: "2026-03-26T11:00:00Z",
    notes: "",
  },
  {
    id: "FS-1044",
    customer_name: "Peter Kimani",
    customer_phone: "0769 111 222",
    items: [
      { product_id: "p7", product_name: "Clay Bricks (1,000)", qty: 2, unit_price: 185000, unit: "lot", subtotal: 370000, vendor_id: "vendor-2" },
      { product_id: "p8", product_name: "Washed River Sand", qty: 5, unit_price: 65000, unit: "tonne", subtotal: 325000, vendor_id: "vendor-2" },
    ],
    total: 695000,
    commission: 55600,
    vendor_payout: 639400,
    delivery_fee: 8000,
    status: "confirmed",
    delivery_address: "Sakina, Arusha",
    created_at: "2026-03-27T08:15:00Z",
    notes: "Call before delivery",
  },
  {
    id: "FS-1045",
    customer_name: "Grace Mwangi",
    customer_phone: "0736 555 888",
    items: [
      { product_id: "p13", product_name: "Floor Tiles 60×60cm", qty: 50, unit_price: 22000, unit: "m²", subtotal: 1100000, vendor_id: "vendor-1" },
      { product_id: "p10", product_name: "Crown Paint Silk White 20L", qty: 3, unit_price: 95000, unit: "tin", subtotal: 285000, vendor_id: "vendor-1" },
    ],
    total: 1385000,
    commission: 110800,
    vendor_payout: 1274200,
    delivery_fee: 12000,
    status: "pending",
    delivery_address: "Arusha CBD",
    created_at: "2026-03-28T07:45:00Z",
    notes: "",
  },
  {
    id: "FS-1046",
    customer_name: "Hassan Juma",
    customer_phone: "0784 321 654",
    items: [
      { product_id: "p11", product_name: "PVC Water Pipe 4\"", qty: 20, unit_price: 28000, unit: "piece", subtotal: 560000, vendor_id: "vendor-3" },
      { product_id: "p12", product_name: "PVC Drainage Pipe 6\"", qty: 10, unit_price: 19500, unit: "piece", subtotal: 195000, vendor_id: "vendor-3" },
    ],
    total: 755000,
    commission: 60400,
    vendor_payout: 694600,
    delivery_fee: 8000,
    status: "pending",
    delivery_address: "Kaloleni, Arusha",
    created_at: "2026-03-28T09:10:00Z",
    notes: "Need PVC cement glue too — will call",
  },
];

export const DELIVERY_TASKS: DeliveryTask[] = [
  {
    id: "dt-1",
    order_id: "FS-1043",
    vendor_name: "Jua Kali Mabati Works",
    pickup_location: "Sakina — Moshi Rd",
    delivery_location: "Kijenge, Arusha",
    items_count: 30,
    status: "in_transit",
    customer_name: "Amina Rashidi",
    estimated_time: "45 min",
  },
  {
    id: "dt-2",
    order_id: "FS-1044",
    vendor_name: "Safari Building Supplies",
    pickup_location: "Kaloleni — Nairobi Rd",
    delivery_location: "Sakina, Arusha",
    items_count: 2,
    status: "ready_for_pickup",
    customer_name: "Peter Kimani",
    estimated_time: "1 hr 20 min",
  },
  {
    id: "dt-3",
    order_id: "FS-1045",
    vendor_name: "Kilimanjaro Hardware",
    pickup_location: "Arusha CBD — Sokoine Rd",
    delivery_location: "Arusha CBD",
    items_count: 53,
    status: "pending",
    customer_name: "Grace Mwangi",
    estimated_time: "Awaiting confirmation",
  },
  {
    id: "dt-4",
    order_id: "FS-1042",
    vendor_name: "Kilimanjaro Hardware",
    pickup_location: "Arusha CBD — Sokoine Rd",
    delivery_location: "Njiro, Arusha",
    items_count: 30,
    status: "delivered",
    customer_name: "John Mollel",
    estimated_time: "Completed",
  },
];

export function getVendorById(id: string) {
  return VENDORS.find((v) => v.id === id);
}

export function getProductById(id: string) {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductsByVendor(vendorId: string) {
  return PRODUCTS.filter((p) => p.vendor_id === vendorId);
}

export function getOrdersByVendor(vendorId: string) {
  return ORDERS.filter((o) => o.items.some((i) => i.vendor_id === vendorId));
}
